---
language: python

before_script:
  - pip install -r requirements.txt

script:
  - yamllint ./ -c ./.yamllint
  - flake8 ./

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
